-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Mar 11, 2025 at 05:33 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `interior_solutions`
--

-- --------------------------------------------------------

--
-- Table structure for table `designs`
--

CREATE TABLE `designs` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `category` varchar(100) NOT NULL,
  `design_type` varchar(100) NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `likes` int(11) DEFAULT 0,
  `used_count` int(11) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `designs`
--

INSERT INTO `designs` (`id`, `name`, `category`, `design_type`, `image`, `description`, `price`, `likes`, `used_count`) VALUES
(1, 'Axolotl', 'kitchen', 'island kitchen', 'img/axolotl1.jpg', 'Axolotl accommodates the common and most practical elements of a contemporary island kitchen in a popular fashion. The island is designed with bottom cabinets for extra storage space and with a Glossy white finish. The kitchen cabinets are built using water-resistant Gurjan plywood, which is known for its strength, durability and water resistivity. Additionally, the thick laminates in a beautiful Glossy White and Walnut Bronze finish surely boosts the interior quality. Contact us through our branches across south India to furnish your kitchen interior like this.', 90000.00, 481, 84),
(2, 'Avocado', 'kitchen', 'island kitchen', 'img/avocado.jpg', 'Avocado is a small modular design made in a mix of Classy grey wood and Frosty white themes. Even though small it has sufficient storage facilities anyone would expect in a typical contemporary kitchen. Its premium cabinets are highlighted with a touch of stainless steel finish handles. As an added feature, the designers incorporated quality soft close doors and drawers for the kitchen. Accessories such as cutlery tray, waste bin, and bottle pull out are also included with this kitchen package. Additional features can be included as per the customer requirements. Visit our showroom and meet our designers to customize this kitchen for your flat.', 100000.00, 511, 63),
(3, 'Amethyst', 'kitchen', 'island kitchen', 'img/amethyst.jpg', 'Bring in a charming and classic feel to the living room with Amethyst. It is an attractive bar counter table with drawers and small open shelves. This unit made of premium Hardwood Fiberboard has a vibrant dual-color finish, making it suitable for almost all interiors. In addition, the counters feature ambient lighting. The sophisticated contemporary aesthetics make Amethyst an ideal solution to spending salient time with family and friends. Contact DLIFE showroom across India and add this beautiful bar counter along with other interior works for a perfect tranquil environment.', 110000.00, 224, 27),
(4, 'Aureolin', 'kitchen', 'island kitchen', 'img/aureolin.jpg', 'Add extra seating, personal style, and storage to kitchen spaces with Aureolin. Blended with contemporary modern aesthetics, Aureolin combines laminated marine ply and Hardwood fiber board in mystic walnut finish and frosty white. Designed with innovative styling, Aureolin comes with premium aluminum finish drawer handles in a soft close mechanism. The Counter top is finished in a galaxy granite slab. The hood and hob is placed at the center making the kitchen space efficient. This island kitchen design is spacious enough to give plenty of room for storing appliances both small and large size. Aureolin provides you sufficient space and individual freedom to spend precious time with family with its advanced state of the art functions. Get the help of interior solution designers anywhere in South India to design, produce and install modular kitchens.', 105000.00, 310, 100),
(5, 'Auburn', 'kitchen', 'island kitchen', 'img/auburn.jpg', 'A stylish wardrobe cum study table built with Hardwood Fiberboard in frosty white and elevated wood finish. This unit has a large 2-door wardrobe, study table space for a single person and overhead storage cabinets. The countertop has enough space for using laptops and study materials. The wardrobe cum study unit also features ambient lighting reflecting contemporary tastes and requirements. An open space is also provided below the overhead cabinets for keeping books.  Size of the wardrobe can be altered as per measurements of the bedroom and according to the needs of the customers. Other modifications can also be done as per requirements', 120000.00, 263, 51),
(6, 'Cypress', 'kitchen', 'island kitchen', 'img/cypress.jpg', 'Cypress is a contemporary island kitchen design with attractive cabinets and a beautiful island. The kitchen is built using 100% water-resistant Gurjan plywood, which makes it durable in extreme wet conditions as well. The thick laminate coating over the plywood in a Walnut Bronze and Glossy White finish further improves the material’s strength and durability. Besides the rare and quality material, the kitchen is also equipped with spacious cabinets, open ledges, and soft close shutters. Corian top is used as the countertop to match with the color combinations of the laminate. The red colored decorative lights placed above the hob further enrich the beauty of these units. Our expert interior designers can include your suggestions and modify this kitchen as per your requirements. Visit our showrooms or request for an estimate to get more details and price.', 90000.00, 168, 37),
(7, 'Bark', 'kitchen', 'island kitchen', 'img/bark.jpg', 'Creativity has no limits in contemporary interior designing. Let it be a modular kitchen or a complete home interior, contemporary style is a brilliant approach to make the interior more attractive. This premium island kitchen is equipped with a beautiful and convenient breakfast counter. Designer has managed to separate one part of the island as a breakfast counter whereas the other part houses the hood and hob. This kitchen provides adequate lower cabinets and tall units limiting upper cabinets, making better use of ventilation. Customers can further add or remove cabinets or accessories as per your requirements. Contact us to discuss details and possibilities of customization as per the size and shape of your flat or villa.', 85000.00, 149, 25),
(8, 'Niagara', 'kitchen', 'island kitchen', 'img/niagara.jpg', 'With its compact dimensions and customization facility Niagara offers a perfect fit for apartment interiors with limited space availability. This island kitchen has compact dimensions and an extremely grounded and realistic design. Everything inside the kitchen is designed by analyzing the room area and by finding opportunities in it. Be it the island or the tall unit, our interior designers stay with this realistic approach to overcome space limitations. A combination of Mystic Walnut and Frosty White laminate is used for cabinets and accessories, which is amazingly beautiful. The hood and hob are placed on the island, and the sink is placed on the opposite side. Customers can visit any of our branch offices or showrooms to discuss kitchen designs for your apartments.', 95000.00, 272, 44),
(9, 'Orchid', 'kitchen', 'island kitchen', 'img/orchid.jpg', 'When it comes to kitchen interior design, everyone has different tastes and specific lifestyle requirements. Some prefer simple and functional designs with minimal luxury while others search for luxurious kitchens that are mesmerizing to watch. Interior Solutions Orchid is surely a visual treat, and is loaded with premium accessories. Starting from the premium dual color finish to the Galaxy Black countertop, the kitchen maintains its uniqueness everywhere. Moreover, it is loaded with essential stainless steel accessories and a convenient tall unit. The designer has used Mystic Walnut and Glossy White laminate to obtain this flawless and beautiful theme. The traditional cabinet doors are replaced with advanced soft close doors and shutters, which are clearly functional and far more easy to use. This design may be perfect if you are searching for a spacious modular kitchen in modern style. Our interior designers can help to customize this to perfectly fit your kitchen.', 123000.00, 524, 97),
(10, 'Talisman', 'kitchen', 'l shape kitchen', 'img/talisman.jpg', 'Talisman is an elegant looking L shaped modern kitchen furnished in California scrub oak and frosty white finish. Aluminum profile handles are used with the square edge shutters for durability and style. Other materials used for giving a perfect finish to storage cabinets are high-quality Marine ply and all side laminated Hardwood Fiber Board. Sizes of bottom and overhead storages can be customized as per the requirement of the customer. Premium quality hood & hob and modular kitchen accessories are other features of this model. ', 115000.00, 389, 77),
(11, 'Cyclone', 'kitchen', 'l shape kitchen', 'img/cyclone.jpg', 'Cyclone – L shaped Modular kitchen design with wooden Canadian Walnut finish as per the requirement of the customer by interior designers in Ernakulam. Galaxy Black granite top and Canadian Walnut storage cabinets make a perfect color combination. High-quality Marine ply and all side-laminated hardwood fiber board used are durable and giver an elegant external look. Other furnishings for flats or houses are also provided along with branded standard and premium kitchen accessories.', 155000.00, 651, 129),
(12, 'Ebony', 'kitchen', 'l shape kitchen', 'img/ebony.jpg', 'Small or medium sized ‘L’ shape kitchens are the perfect way to overcome the space limitations inside your apartment interiors. Ebony ‘L’ shaped modular kitchen design preserves every square inch of the space, and effortlessly turns those into beautiful storage and work areas. The less cluttered layout of overhead cabinets around the windows maintains the airflow inside the kitchen. As a result, the interior looks more spacious even after including more storage cabinets at the bottom. Premium features such as soft close doors, hettich accessories, stainless steel hood and hob, and Galaxy Black granite counter etc. comes as a standard option with this ‘L’ shaped modular kitchen design.', 105000.00, 259, 73),
(13, 'Sapphire', 'kitchen', 'l shape kitchen', 'img/sapphire.jpg', 'Sapphire L shaped modern kitchen is meant for kitchens having average or lavish space and is designed in a contrasting color combination of Walnut bronze and Frosty White. The dry and wet area is separated by placing hood and hob at one part of L shape and sink on the other portion. Overhead cabinets are arranged above the sink with space for GTPT. Both sides of the hood are equipped with open shelves and ledges. Granite slab in Misty dream black color is used for countertop. Customers can get it customized according to their ideas and as per measurements of the kitchen.', 105000.00, 247, 56),
(14, 'Sunray', 'kitchen', 'l shape kitchen', 'img/sunray.jpg', 'Sunray has a slate grey  and white finish which is delicate and delightful. It comes with plenty of storage space including overhead and bottom cabinets and tall units. The kitchen also gets a Hood & Hob, and the sink is in the center of the other part. Sunray provides spaces for the oven and grill while giving your kitchen a light and spacious look. Granite slab is used for the countertop. Kitchen accessories can be included and customization can be done if required for this modular kitchen.', 100000.00, 499, 177),
(15, 'Harlequin', 'kitchen', 'l shape kitchen', 'img/harlequin.jpg', 'The co-existence of style, practicality and durability is the secret of a successful kitchen interior. Interior Solutions Harlequin perfectly maintains these qualities effortlessly; it is elegant, good looking, and practical in every sense. The unit has a premium theme with a mix of Misty Oak and Glossy Black shades, which is unique and ravishing to see. The kitchen has a beautiful tall unit with built-in space for the oven attached to its right end. The soft close doors and stainless steel accessories retain the premium feel of the kitchen.', 118000.00, 339, 70),
(16, 'Erin', 'kitchen', 'l shape kitchen', 'img/erin.jpg', 'Designed in a way that evokes memories, Erin L shaped modular kitchen is crafted in Dark Cytrus and Glossy White finish. Built using all side laminated Marine Ply and Hardwood Fiber Board, this kitchen unit encompasses durability and style. Erin comes with open shelves and overhead cabinets to keep you organized and cherish some of the happiest moments of life. Cabinet’s works in soft close mechanism ensure that the shutters are always closed properly. This unit is 100% customizable and made as per requirements in Karnataka, Tamil Nadu, Kerala and Telangana to utilize maximum space of the kitchen.', 125000.00, 390, 104),
(17, 'Arizona', 'kitchen', 'l shape kitchen', 'img/arizona.jpg', 'Tailored for the ones that prefer versatility, Arizona is a dream come true. Designed with long lasting Hardwood MDF in Canadian walnut finish and horizontal white bands, this bed ensures durability. This bed combines contemporary design with a long countertop like table to give a chic look that encompasses artisanship. The glossy black and frosty white tone gives a visual interest and gives the bed a handsome appeal. Arizona features contemporary design that makes it wonderful in any bedroom. Contact or visit our nearest showroom to have an exclusive walkthrough of this custom bed design.', 122000.00, 374, 84),
(18, 'Licorice', 'kitchen', 'l shape kitchen', 'img/licorice.jpg', 'Licorice kitchen has an elegant design and has a unique dual tone glossy finish. Hood and Hob is fixed at the middle region of one part of L shape. Overhead cabinets are arranged to the right of the hood and small open shelves are provided at the left of it. The sink is placed at the other side of the L. Essential stainless steel kitchen accessories are also included with this. You can choose any available color as of your choice for this modular kitchen for houses or flat in Kerala and Bangalore. Other customization can also be done according to your idea and availability of space in the kitchen.', 135000.00, 439, 64),
(19, 'Beige', 'kitchen', 'l shape kitchen', 'img/beige.jpg', 'Biege is a flexible modular kitchen design to suit both small and larger spaces. One of the best attributes of this contemporary L Shaped Kitchen design is its vast and spacious Galaxy Black countertop.  This helps the users to maintain the cooking and cleaning area neat and less congested. Moreover, its Black appearance feels non-intrusive and seamlessly blends in with Canadian Walnut finish of the cabinets. The kitchen almost has a square ‘L’ layout with the sink is attached on the center of one leg and the hob being the center of the other. With a few additional modifications, this model can be made perfectly suitable for house or apartment interiors in any size.', 130000.00, 589, 177),
(20, 'Wave', 'kitchen', 'l shape kitchen', 'img/wave.jpg', 'Wave modular kitchen design has a simple design element but graceful and stylish appearance. This kitchen has a dual color combination of walnut bronze and slate grey for overhead cabinets and bottom storage units. The attached overhead and bottom cabinets with ample lighting are sufficient for storage. Wave also gets a Galaxy Black granite slab which serves as the countertop. It can be customized as per requirements and according to measurements of the kitchen and would be a major game-changer in small apartments.', 150000.00, 889, 277),
(21, 'Cocoa', 'kitchen', 'l shape kitchen', 'img/cocoa.jpg', 'Customized modular kitchens are no longer a ‘new-age’ phenomenon. People do not consider these as a luxury anymore; it is a necessity rather than a luxury. Once it was considered expensive for middle-class families. However, when the competition arose, newer and better models came in with more aggressive pricing, sometimes even less than that of the ready-made ones. Cocoa is one such a design made in a classic formula that succeeded in attracting the buyers across South India. It is equipped with premium Hettich accessories and has everything you would want inside a kitchen. Be it the mixed color theme or the Galaxy Black countertop, everything follows a fluidic design pattern and comes with a premium finish.', 115000.00, 379, 79),
(22, 'Peru', 'kitchen', 'l shape kitchen', 'img/peru.jpg', 'This modern modular Kitchen made in L Shape design  has a chic design with a dual color finish. You can really bring out the beauty of your home with this kitchen design. The kitchen also boasts a Galaxy Black granite slab which is used as the countertop. Stainless steel kitchen accessories are well arranged in the drawer storages. Any kind of customization can be done according to the taste of the customer and as per measurements of the kitchen.', 119000.00, 279, 101),
(23, 'Amber', 'kitchen', 'l shape kitchen', 'img/amber.jpg', 'Modular Kitchen, Amber is an ideal choice for flats, villas, and houses who are in need of a large storage area. This ergonomically designed contemporary style L shaped kitchen design has a beautiful finish in Walnut Bronze theme; a touch of Glossy White is also mixed here and there to enrich the visual appeal. Furthermore, the smooth and Glossy countertop adds more uniqueness to the kitchen. The designers provided spacious cabinets at the bottom of the kitchen with soft close doors and shutters.', 114000.00, 381, 87),
(24, 'Snow', 'kitchen', 'l shape kitchen', 'img/snow.jpg', 'Snow is a stylish modular kitchen having a contrasting dual-tone design in a California scrub oak and Frosty White finish. This contemporary modular kitchen can easily blend in with most interior themes due to its well-organized color theme. This model is packed with all the essential gadgets for an ideal kitchen. The kitchen has both closed and open kitchen cabinets with recessed lighting, and the sink is placed on its left side. Designers chose a frosty white for the overhead cabinets while the bottom cabinets get California scrub oak laminates. This selection makes the kitchen interior more unique and refreshing. Each client can further optimize the size, shape, and measurements of this modular kitchen by discussing it with our designers.', 125000.00, 489, 106),
(25, 'Berry', 'kitchen', 'parallel kitchen', 'img/berry.jpg', 'Berry modular kitchen has compact dimensions; this makes it perfect for small and medium sized apartment interiors. This durable stylish parallel kitchen with compact cabinets is decorated with two beautiful color laminates, Polar Blue color being the primary and Glossy White the secondary. The cabinet doors and shutters are further delighted by the addition of stainless steel door and drawer handles. Galaxy Black granite slab is used as the countertop along with Hettich kitchen accessories. The whole kitchen unit is machine made, thus ensuring a perfect and uniform finish. Furthermore, the addition of soft close doors and transparent glass cabinets makes it more usable. Clients can directly visit our showroom to see this model and its possibilities when customized for your home interior.', 200000.00, 1055, 454),
(26, 'Walnut', 'kitchen', 'parallel kitchen', 'img/walnut.jpg', 'Walnut is a simply designed parallel kitchen perfect for houses as well as flats and villa interiors. The unit is suitable for kitchens with limited space availability. The cabinets are provided with a dual tone finish. Creating a balanced vibe, this modular kitchen design also gets Galaxy Granite slab that is used as the countertop and hood & hob, sink and massive storage at the sides. Walnut can be fully customized, as per requirement. Contact our interior designers in Kerala, Karnataka, Telangana, Maharashtra, or Tamil Nadu now.', 120000.00, 584, 223),
(27, 'Keet', 'kitchen', 'parallel kitchen', 'img/keet.jpg', 'Keet is a very popular parallel kitchen model, made of boiling waterproof marine plywood with thick and beautiful laminates. This model has all the modern features of a premium contemporary modular kitchen such as soft close doors, metallic finish on the cabinet edges plus Hettich accessories. The kitchen cabinet is decorated in a Walnut Bronze finish and Galaxy Black granite slab is used as a countertop. Sink and Glass Tray Plate Trays are placed on one side of the parallel units, the hood and hob is fixed on the center of opposite side. Additional storage space can be added as per the customer requirements. Visit the nearest Interior Solutions showroom to customize this modular kitchen for your house or flat interiors across South India.', 100000.00, 355, 154),
(28, 'Parakeet', 'kitchen', 'parallel kitchen', 'img/parakeet.jpg', 'Parakeet is a fully-fledged Kerala modular kitchen design with an equally attractive color theme. This kitchen comes in a dual color combination of Frosty White and Walnut Bronze wooden finish. It has plenty of storage facilities in the form of bottom cabinets and open shelves. Hood and Hob are placed at the center of one side of the parallel unit. Parallel unit at the opposite side comes with overhead cabinets and open shelves. Boiling waterproof marine plywood is used for cabinets whereas Galaxy Granite slab serves as the worktop. Meet our designers to check the customization options for this kitchen.', 90000.00, 407, 333),
(29, 'Crescent', 'kitchen', 'parallel kitchen', 'img/crescent.jpg', 'Crescent is a water-resistant parallel kitchen design with premium cabinets, soft close doors, and Hettich accessories. Overhead cabinets are extremely functional, unique and specially designed to maintain the sophisticated appearance. This modular kitchen design in metallic silver and frosty white is the perfect example that even a small space can look sleek and put-together. Clients can further modify this modular kitchen as per space and requirements. Visit us or contact our interior designers now.', 200000.00, 400, 199),
(30, 'Mint', 'kitchen', 'parallel kitchen', 'img/mint.jpg', 'Mint is a modern parallel kitchen design with contemporary style cabinets and fixtures with a classic vintage color theme. Even though the kitchen interior may seem small at first, it has an excellent space to utilization ratio than most popular modular kitchen models. The bottom cabinets of this kitchen are astoundingly spacious and are equally attractive with the classic Glossy White finish. With the help of interior contractors in Cochin, this parallel kitchen can be customized as per the space available. Meet our designer in one of the 3 showrooms in Kochi and discuss!', 150000.00, 916, 404),
(31, 'Turmeric', 'kitchen', 'parallel kitchen', 'img/turmeric.jpg', 'This parallel kitchen design has a unique color combination with the bottom cabinets decorated in a rare Cardinal Red finish and overhead cabinets in a Frosty White finish. Furthermore, the drawer and cabinet handles have a stainless steel finish. Galaxy Black granite slab is used as the countertop. To maintain the quality of the kitchen interior, Hettich kitchen accessories are also included in the package. The major advantage of this kitchen is that we could make it perfectly fit into your kitchen by customizing it as per the actual measurements.', 109000.00, 115, 54),
(32, 'Misty', 'kitchen', 'parallel kitchen', 'img/parallelkitchen1.jpg', 'Misty is a small, beautiful, and highly functional parallel kitchen for apartments in a dual tone finish with walnut bronze and slate grey finish.  For urban apartments in Cochin, Bengaluru and Chennai, this grey color scheme with woody accents would be perfect and striking. Kitchen cabinets, drawers, stove, sink and open shelves are well arranged and are positioned within the reach. Size of overhead and bottom storage units can be further optimized by the designer according to the measurements of the kitchen.', 180000.00, 777, 420),
(33, 'Pearl', 'kitchen', 'parallel kitchen', 'img/pearl.jpg', 'Pearl is a partial partition unit which can be used to separate living and dining room interiors. The unit consists of horizontal panels in Walnut Brown is partial and see-through, however, it does help to maintain a separate aura in both the rooms. It is always essential to customize these units in order to fit in perfectly in the desired area. Customers can visit our nearest showroom and meet our top interior designers in Kerala to get it customized as per your needs.', 150000.00, 333, 111),
(34, 'Coral', 'kitchen', 'parallel kitchen', 'img/coral.jpg', 'The primary intention of customized interior furnishing is to utilize the leftover space and maximize the functionality. This same formula is applicable to wash counters as well; an ideal unit like Coral fits in perfectly in any space allotted. Coral is such an ideal modern wash counter design, which is specifically made to match the contemporary apartment interiors. The unit is designed in such a way that the modifications in the dimensions will not affect its aesthetic quality. The wash unit design can be customized to any size, shape, or color theme to match with the rest of the interiors.', 140000.00, 256, 84),
(35, 'Chestnut', 'kitchen', 'parallel kitchen', 'img/chestnut.jpg', 'When it comes to bedroom interiors, small sized minimalist furniture may not always be the perfect choice. Chestnut is a practical and user-friendly wardrobe cum study unit when it comes to its intended applications. From the ergonomically designed closet and internal systems to the well-diverged double study unit in a mixture of midnight blue, frosty white and slate grey theme, it is practically one of the finest examples of kid’s room furniture units. Furthermore, a cluster of open shelves and drawers are also provided to enhance user convenience.', 135000.00, 399, 187),
(36, 'Cario', 'kitchen', 'straight kitchen', 'img/cario.jpg', 'Interior Solutions Cario is a classic modular kitchen with a beautiful theme, which resembles the traditional kitchen interiors. This kitchen model is useful and functional like any modern modular kitchen. The kitchen is equipped with a tall unit, spacious cabinets and numerous drawers, all of which are made of strong and quality materials with high durability. The kitchen cabinets and tall units have a Wenge finish, whereas Galaxy black granite slab is used as the countertop. To know more about this kitchen, meet our consultants or designers in Maharashtra, Kerala, Telangana Tamil Nadu, or Karnataka.', 95000.00, 160, 48),
(37, 'Moroccan', 'kitchen', 'straight kitchen', 'img/moroco.jpeg', 'Moroccan has a perfect finish in a mix of slate grey and California scrub oak theme. Apart from the cabinets, this kitchen is amazingly decorated by the perfect use of color combinations in the accessories as well. The cabinet and drawers are provided with a soft close mechanism whereas Galaxy Black granite slab takes position as the countertop. Unlike the regular straight kitchen designs, this kitchen is unique with each overhead cabinet having different sizes and ample storage. Further customization can be done as per the client’s suggestions and choices. Contact the nearest D’LIFE showroom for more details on modular kitchen customization options.', 115000.00, 314, 115),
(38, 'Siam', 'kitchen', 'straight kitchen', 'img/siam.jpg', 'Siam is one of the most practical kitchen designs you can implement on apartments, where the room size is limited. This compact straight kitchen model has spacious bottom cabinets and drawers with a soft close facility. A couple of overhead cabinets are also provided on the right side for additional storage. The luxurious yet minimalistic design this modular kitchen design carries cleverly excludes the need of a conventional kitchen and accessory items, which occupy considerably large space. Contact us to design, make and install this modular kitchen in Karnataka, Telangana, Kerala or Tamil Nadu.', 155000.00, 682, 208),
(39, 'Mystic', 'kitchen', 'straight kitchen', 'img/mystic.jpg', 'Mystic is a modern straight kitchen design with a minimalistic yet functional design. The kitchen has a Walnut Bronze and Glossy White finish, with the bottom cabinets are provided with a Walnut Bronze finish and the overhead cabinet with a Glossy White finish. Galaxy Black granite is used as the countertop. Additional features like soft close doors and Hettich accessories are also provided with this kitchen. To enhance the visual appeal, a stainless steel touch is also added at the drawer handles. The hood and hob is located towards the right end of the kitchen, and a few open shelves are provided on its left side for user convenience. Contact us to get more details about Mystic modular kitchen design and contract.', 130000.00, 316, 187),
(40, 'Blackcurrant', 'kitchen', 'straight kitchen', 'img/blackcurrent.jpg', 'Blackcurrent is a small, convenient, and attractive kitchen design that would be suitable for home interiors in Cochin, Bangalore etc. It has well optimized cabinets and premium appearance, which makes it easily one of the best straight kitchen models in the current market. The designers incorporated a mix of open and closed cabinets in the overhead section. As a result, the kitchen has plenty of overhead storage spaces than most conventional straight kitchen designs. The overhead and bottom cabinets are decorated in a Glossy White and Black finish whereas the identical open shelves are highlighted in a Dark Citrus theme. Contact or visit the nearest DLIFE branch to design and build this modular kitchen as per your style and kitchen measurements.', 105000.00, 260, 96),
(41, 'Mat', 'kitchen', 'straight kitchen', 'img/mat.jpg', 'Marie Gold has always been a beautiful choice for interiors. However, not a lot of designs utilize this color combination for kitchen interiors. In Mat, the designer cleverly utilizes this color along with a small touch of Black and makes the design unique and refreshing. This ergonomically balanced kitchen unit has plenty of storage space as bottom and overhead cabinets. Moreover, the full-size tall unit and the nearby open shelves also may help to solve the customer’s storage needs. Designers positioned the hood and hob towards the left and the tall units on the opposite side.  Customers can further modify it as per their needs and requirements. Our top designers at Maharashtra, Karnataka, Telangana, Tamil Nadu and Kerala showrooms will assist you in customizing this kitchen as per your suggestions.', 85000.00, 159, 78),
(42, 'Tanned', 'kitchen', 'straight kitchen', 'img/tanned.jpg', 'Tanned has a unique Glossy finish with a thick laminate in frosty white and walnut bronze color. The kitchen is equipped with plenty of modern and advanced features, which would clearly outmatch its rivalries. Soft close shutters, Hettich accessories, built-in oven space, hood & hob just to name a few. Galaxy black granite is used as the countertop, whereas water-resistant Gurjan plywood is used to make cabinets and shutters. This combination of premium quality materials and accessories make this kitchen a perfect choice for modern home interiors. Client’s who are interested in this kitchen model can contact us to get more details about the kitchen or to know the possibilities of customization.', 100000.00, 245, 158),
(43, 'Glossy', 'kitchen', 'straight kitchen', 'img/glossy.png', 'Straight kitchen is always convenient and space saving, if you design it well by considering your requirements and the interior layout. Glossy is an ideal medium-sized straight kitchen design with a genuinely attractive color theme. Besides the appearance, this kitchen offers a lot more when it comes to functionality and quality. Its well-furnished drawers and spacious cabinets offer board storage facility and premium finish. This kitchen is further enriched by the addition of Hettich accessories and stainless steel door handles. Apart from the top and bottom cabinets, small open ledges are also provided next to the hood and hob for convenience. Visit any of our showrooms to get more details of this classic straight kitchen design.', 140000.00, 360, 222),
(44, 'Moldau', 'kitchen', 'u shape kitchen', 'img/modular.jpg', 'This ‘U’ shaped kitchen is unique because of its nontraditional, yet beautiful color theme. The major advantage of Moldau kitchen is that it can be made suitable for almost all types of houses, and apartments. Its medium size and attractive color theme make it easy to blend in with most interior themes. Moreover, our expert designers at the showrooms may further improve the kitchen’s utilities and color choices by customizing it as per the customer’s requirements and the interior theme. The premium soft close doors and stainless steel accessories is another added advantage. Contact us or visit our showrooms to design and furnish this kitchen for your home.', 100000.00, 200, 109),
(45, 'Ghana', 'kitchen', 'u shape kitchen', 'img/ghana.jpg', 'Ghana is a contemporary modular kitchen design, which excels in every aspect of modern kitchen furnishing. It has plenty of perfectly symmetrical cabinets made of water-resistant Gurjan ply, covered with premium slate grey and frosty white laminates. The kitchen also gets small open shelves on the right, to store essentials and spices. The well-balanced ambient lighting and the contrasting color combinations on the upper cabinets make this kitchen interior a sure delight to watch. Ghana- modular kitchen is available through our showrooms in Kerala, Bangalore and Tamilnadu. Customers can walk-in and discuss the details with our interior designers.', 105000.00, 212, 149),
(46, 'Maple', 'kitchen', 'u shape kitchen', 'img/maple.jpg', 'Water-resistant Gurjan plywood is clearly the finest material for kitchen cabinets and shutters. It is water resistant, durable and offers a great finish when combined with top quality laminates. This kitchen uses 100% Gurjan plywood and integrates tall units to improve the user convenience. Moreover, the designers incorporated soft close doors and shutters. Everything inside the kitchen, including hood and hob, the space for the refrigerator, and sink are perfectly positioned to reduce the user’s efforts. Client’s can visit any of our showrooms cum branch office to get this kitchen custom made for your home.', 160000.00, 444, 259),
(47, 'Carlton', 'kitchen', 'u shape kitchen', 'img/carlton.jpg', 'This ‘U’ shaped kitchen is well equipped with premium cabinets, accessories, and tall units. The tall unit provided at the left side houses the oven and offers additional storage space. The sink is fixed on the center of the ‘U’ and a small overhead cabinet with a transparent glass door is provided on its left side. Kitchen cabinets are decorated in a dual color finish by a durable and thick laminate coating. Standard Hettich accessories are included in the package; additional items can be added as per the client requirements. Meet interior designers at our showrooms in Kerala and Bangalore to customize and make a kitchen as per your requirements.', 90000.00, 183, 88),
(48, 'Sappy', 'kitchen', 'u shape kitchen', 'img/sappy.jpg', 'Not everyone has the luxury of a large and spacious modular kitchen in their apartments. Especially the flat interiors in metro cities like Cochin, Bangalore and Chennai, where the space availability is comparatively less, and most house owners prefer a small yet convenient kitchen. Sappy is a perfect design for such homes, it is compact, stylish and is made of premium quality materials. Furthermore, our top interior designers at the showrooms could improvise the kitchen interiors and utilities as per your choice. Contact DLIFE interior contractors to view and modify this kitchen for your apartment.', 130000.00, 325, 159),
(49, 'Anegre', 'kitchen', 'u shape kitchen', 'img/anegre.jpg', 'Anegre is a popular kitchen model suitable for small or medium-sized modern home interiors. The cabinets and shutters are made using water resistant Gurjan plywood with long durability, whereas the doors, and drawer handles are made of stainless steel. These materials ensure the kitchen’s long durability without any considerable maintenance or touch up works. Additionally, premium Hettich accessories are provided with this kitchen, thus eliminating even the slightest chance of corrosion. Client’s can visit our showrooms to discuss more about your interior requirements and modular kitchen. Expert designers at DLIFE interior contractors will help you to customize Anegre to match your style and needs.', 110000.00, 211, 136),
(50, 'Sapeli', 'kitchen', 'u shape kitchen', 'img/sapeli.jpg', 'Nowadays, people become more observant, and are more concerned about aesthetic finish than earlier. Sapeli is an elegant design, which incorporates the luxury that everyone deserves in their kitchen without losing its functionality. In addition, the kitchen is equipped with Hettich accessories, and soft close shutters to maintain the luxury. The hood and hob is placed at the center of the ‘U’, and sink is placed next to it on the left side. Cabinets with transparent glass shutters are also provided to store cutleries. Contact the nearest showroom of DLIFE interior designers and contractors to get this custom-made ‘U’ shape kitchen in Bangalore or Kerala.', 140000.00, 400, 199),
(51, 'Brunette', 'kitchen', 'u shape kitchen', 'img/brunette.jpg', 'The specialty of Brunette kitchen design is its fluidic design consisting of two beautiful color combinations. The design cleverly  makes use of space with double overhead cabinets; floor-to-ceiling wall cabinetry, to accommodate more items. The dual color cabinets of walnut bronze and frosty white are so on-point. This signature u shape modular kitchen design can be further customized to match the client’s requirements. Contact or visit any of our showrooms, and meet our best interior designers to furnish this modular kitchen in Bangalore, Kerala or Tamilnadu.', 100000.00, 203, 119),
(52, 'Pine', 'kitchen', 'u shape kitchen', 'img/pine.jpg', 'Interior Solutions pine is a premium U shape modular kitchen in a stylish Mystic Oak finish. The kitchen is equipped with large tall units and spacious cabinets. For a better experience, the designers incorporated a soft close facility to cabinet doors and drawers with a stainless steel finish. Galaxy Black Granite slab is used as the countertop. The kitchen is loaded with Hettich accessories to maintain its premium standards. The hood and hob is provided at the center of the ‘U’ with a couple of drawers at the bottom for better convenience. This kitchen is suitable for all types of houses, villas, and apartment interiors in Bangalore, Kerala or Tamil Nadu. D’LIFE provides an option to customize this modular kitchen to suit your family’s needs.', 110000.00, 240, 159),
(53, 'Macaroon', 'kitchen', 'u shape kitchen', 'img/macaroon.jpg', 'Macaroon is larger and spacious than other conventional u-shaped modular kitchen designs. This makes it unique and more attractive for people who are looking for a full-fledged modular kitchen for their house or apartment interiors. The kitchen is equipped with large soft close bottom cabinets and medium-sized overhead cabinets with ambient lighting. All essential kitchen accessories from premium brands are included with this kitchen. Customers can add or remove cabinets or accessories as per their requirements. Our top interior designers at the showroom will customize this design further to fulfill your needs.', 105000.00, 222, 191),
(54, 'Onyx', 'kitchen', 'u shape kitchen', 'img/onyx.jpg', 'Onyx single chairs offer great comfort and elegance within the defined space limit. Bring home this beautiful single chair unit having a compact size and an adorable color theme. This plain single chair has a metallic frame structure, enclosed with a premium fiber casing. There are areas in every home, where the space limit restricts large sofa units or chairs with bulky cushions. Onyx’s primary intention is to provide a seating arrangement in such areas. Additionally, the unit’s adorable design and finish allow it to be an added decoration to the room interior.', 130000.00, 252, 137),
(55, 'Charcoal', 'kitchen', 'u shape kitchen', 'img/charcoal.jpg', 'Charcoal is a spacious modular kitchen, which is suitable for medium and large sized rooms. With its top-notch design quality and aesthetic finish, it definitely stands out among the long list of designs in this popular modular kitchen segment. The kitchen has room for everything you would want in a kitchen. A tall unit with space for an oven is provided on the right side of the ‘U’, and a large space for a refrigerator is left on its left side. Hood and Hob is fixed at the middle portion of the U shape and Sink with GTPT is placed opposite to the tall unit. The tall units and overhead cabinets have a walnut brown finish whereas the bottom storage cabinets are decorated in Frosty White. Contact us or visit our showroom to design this kitchen with changes as per floor plan and suggestions.', 100000.00, 278, 169),
(56, 'Graphite', 'kitchen', 'u shape kitchen', 'img/graphite.jpg', 'Graphite modular kitchen has everything you would expect in a kitchen. It has spacious cabinets, soft close doors, an amazing tall unit and branded kitchen accessories. For this model, the designers fixed the hood and hob at the center portion of the U, and kept the spacious tall unit right next to it. This makes it more convenient for the users to access the tall unit while cooking. Customize Graphite modular kitchen with the help of our designers at showroom network in Kerala Kochi or Bangalore.', 100000.00, 211, 139),
(57, 'Canary', 'kitchen', 'u shape kitchen', 'img/canary.jpg', 'Even though there are several other options people still love the classiness of wooden finish for the furniture. Canary is a six-seat dining table set in walnut bronze theme made using supreme quality hardwood MDF, with thick lamination in wooden finish that gets the whole family together. It closely resembles the gorgeous original wood, and at the same time possesses high strength and durability. Stand this dining set close to your living or kitchen for an easy eye and feeling of opulence. Approach any of our branches to get premium furnishing with complete customization.', 104000.00, 237, 189),
(58, 'Wainscoting', 'bedroom', 'bed', 'img/wainscoting.jpeg', 'The Wainscoting is a perfect designer bed that guarantees you a stylish good night’s rest. It is the perfect designer bed that makes your bedroom feel like the true sanctuary with the right balance of style and comfort. The headboard is cosy enough giving a soothing luxurious feel. Get in touch with our interior designer now or simply walk into our showroom to add this beautiful bed design to your home.', 80000.00, 896, 646),
(59, 'Montreal', 'bedroom', 'bed', 'img/montreal.jpg', 'Contemporary bed designs combine simplicity and a sense of minimalist artistic nature. Minimalism is defined by a sense of ultra sleek lines and functionality. Montreal combines the classic form and modern aesthetics. Crafted in a contemporary form with golden oak wood and slate grey theme, the bed comes with bedside tables that match the dual color combination. Magnificently crafted bed features upholstered headboard to offer a serene look. This bed design uses simple streamlined minimalistic design principles and is entirely customizable based on customer requirements.', 100000.00, 1096, 888),
(60, 'Primrose', 'bedroom', 'bed', 'img/primrose.jpg', 'A great way for storing items is to use wood trunks and cupboards. However, most modern bedroom requirements are aligned with attaining the most storage space they can get. Primrose comes in a bottom storage design and is the complete solution to a modern bed that suits every budget and style with storage needs. The bed design is completely customizable as per customer requirements. It comes with minimalistic white headboards, bottom storage and matching storage cabinets. The storage spaces are useful and help you store plenty of things freeing up space from your cupboard. Contact or visit our nearest Interior Solutions showrooms to have your custom bed design which fits in seamlessly to your room.', 90000.00, 969, 936),
(61, 'Hanoi', 'bedroom', 'bed', 'img/hanoi.jpg', 'Beds are the central element of any bedroom. It is the perfect place to snuggle up, relax and restore energy. Designed in the contemporary architectural form, Hanoi is a bed design appropriate for the ones looking for a modish bed design. Hanoi is crafted in hardwood MDF with all side laminates of slate grey and frosty white finish. The bed is equipped with side tables and bottom storage to give off a superior and classy experience to the space. With the clean and solid construction, Hanoi exudes an up to date fashionable charm to your bedrooms. Contact or visit the nearest DLIFE showroom to have an exclusive walkthrough of Hanoi along with our wide range of bed designs to find your inspiration.', 110000.00, 1050, 895),
(62, 'Tasmania', 'bedroom', 'bed', 'img/tasmania.jpg', 'Tasmania is a sleeping beauty that boasts one-of-a-kind contemporary charm. Inspired by the most sought-after designs, this custom-made designer bed carries the charm and style that makes your bedroom a treasure chest. Crafted with elevated wood and frosty white color on Hardwood Fiberboard, this bed adds glamour with perfect posh to any bedroom. This bed features drawers and a bedside table designed in dual color to enhance the bedroom’s glitz and glimmer. Tasmania is extremely elegant giving it a look that makes you not want to take your eyes off.', 85000.00, 832, 614),
(63, 'Salvation', 'bedroom', 'bed', 'img/salvation.jpg', 'A custom-made bed design with formidable curves and evenly carved decorations is a sure delight to the bedrooms. Salvation is a contemporary king size bed design with a solid rectangular structure. It has a unique theme made using a mix of walnut bronze and frosty white colors interlacing with each other. Salvation is made using premium grade hardwood MDF with thick laminates. The bed also features  bedside tables on both sides. This super-durable material combo ensures the strength and durability of the bed in most weather conditions. Visit a Interior Solutions interior design company in Kerala, Bengaluru or Tamilnadu for more information regarding complete home furnishing.', 90000.00, 906, 700),
(64, 'Morocco', 'bedroom', 'bed', 'img/morocco.jpeg', 'Add contemporary warmness and a cozy ski lodge-like living to the bedroom space with Morocco. Developed with Hardwood Fiberboard and dressed in a slate grey finish, this modern bed enhances the look of any charming space. Spacious under-bed storage and bedside tables with drawers help to organize things better. This timeless bed never goes out of fashion and brings elegance to any space. The headboard and body come with a white glossy stripe adding to its exceptional look. Morocco bed is entirely customizable based on customer requirements and can be made in king and queen sizes.', 95000.00, 969, 751),
(65, 'Dallol', 'bedroom', 'bed', 'img/dallol.jpg', 'Dallol is a majestic timeless design for the ones who prefer efficiency in style. Crafted with all side-laminated hardwood MDF and dressed in Frosty White and Mystic Walnut theme, this bed epitomizes beautiful furniture artisanship. Color inherent to timber gives it a rustic yet modern design. Dallol is a bed with an endless storage option with a bottom and bedside table. This simple space saving enchanter can hoard all your clothing and accessories with its fine construction. The bed features a delightful design giving the bedroom penthouse-suite sophistication.', 85000.00, 796, 496),
(66, 'Arizona', 'bedroom', 'bed', 'img/arizona1.jpg', 'Tailored for the ones that prefer versatility, Arizona is a dream come true. Designed with long lasting Hardwood MDF in Canadian walnut finish and horizontal white bands, this bed ensures durability. This bed combines contemporary design with a long countertop like table to give a chic look that encompasses artisanship. The glossy black and frosty white tone gives a visual interest and gives the bed a handsome appeal. Arizona features contemporary design that makes it wonderful in any bedroom. Contact or visit our nearest showroom to have an exclusive walkthrough of this custom bed design.', 80000.00, 777, 593),
(67, 'Havana', 'bedroom', 'bed', 'img/havana.jpeg', 'Give your bedroom a sleek style of contemporary bed design. Built using all side laminated Hardwood MDF; Havana is a platform bed design that comes with elegant side tables. This treasure trove gives ample space for storing books and essentials. This contemporary style bed is available in both king and queen size with a combination of walnut bronze and frosty white finish. The timeless and trendy design Havana carries adds a flawless look and an inviting appearance. Talk with our interior designers in Tamilnadu, Kerala or Bengaluru to customize Havana as per your taste. This delicately crafted bed is sure to enhance the elegance of any room.', 100000.00, 996, 789),
(68, 'Campion', 'bedroom', 'bed', 'img/campion.jpg', 'Beds that go well with any decor are bliss. Campion is one such design comprising transitional style and trendy design. With headboards in frosty white finish, this is the perfect versatile bed for your creative bedroom. This bed features bottom storage and can accommodate any mattress variations. Rich styling naturally enhances the wooden grain giving it a modern state of the art design touch. Campion is the complete bed set and comes with side tables, quilt, and bedside lamps to immerse you in elegant luxury. It is entirely customizable and is available in king and queen sizes.', 75000.00, 473, 286),
(69, 'Belleza', 'bedroom', 'bed', 'img/belleza.jpg', 'Bring style and comfort to your space. With clean lines and modern style, Belleza is just like what it is entitled. With Clean design in frosty white and mystic walnut finish, Belleza has the beauty and finish that last a lifetime. Belleza is a queen size bed with storage and comes with a bedside table and drawers on either side. The headboard is wide enough to give a refreshing look to your bedroom making you fall in love all over. The headrests extend until the end of the side table to give an enhanced customized finish.', 77000.00, 516, 378);
INSERT INTO `designs` (`id`, `name`, `category`, `design_type`, `image`, `description`, `price`, `likes`, `used_count`) VALUES
(70, 'Bliss', 'bedroom', 'bed', 'img/bliss.jpg', 'Bedroom is a place where you relax, sleep, and share great moments of your day with the closest person in your life. While looking from this perspective, beds are the central and most significant element of a bedroom. Here we present to you Bliss, a customized king size bed design, binding together a well-balanced mix of premium bedroom elements. Bliss’s grand aesthetic finish is formulated by gluing together a fine layer of Merino laminate on premium grade hardwood MDF panels. Visit our showroom to experience the grandeur of customized interior furniture designs and procedure to own it.', 90000.00, 896, 646),
(71, 'Milky', 'bedroom', 'bed', 'img/milky.jpg', 'Human beings have a mean sleep efficiency that has to be satisfied and delighted. This delight starts with the bed we sleep in. Milky is a contemporary bed design made in Hardwood MDF with a blend of frosty white and walnut bronze finish. With its clean line style and craftsmanship, Milky is sure to be a designer inspired contemporary bed design favorite that even your guest will fall in love with. The headboard with a free-flowing look makes it a distinctive piece of art and craft that goes well anywhere. Bed comes with side tables and bottom storage and is available in queen size. It is completely customizable according to customer requirements.', 85000.00, 796, 606),
(72, 'Umber', 'bedroom', 'bed', 'img/umber.jpg', 'Beds, in addition to its practical purpose, add a touch of luxury and charm to any bedroom. Blending both traditional and contemporary aesthetics, Umber is the perfect addition to the master or guest bedroom. Crafted in Hardwood MDF in black glossy and frosty white finish, this traditional yet contemporary style queen size bed design is sure to give a look that matches every decor. The dual color headboard gives an extra touch of elegance and comfort to it adding a refined feel to your bedroom. Umber is the simple, modern style bed with bottom storage that you’ve always dreamed of. For queries, contact or visit the nearest Interior Solutions showroom.', 110000.00, 1069, 966),
(73, 'Grey', 'bedroom', 'bed', 'img/grey.jpg', 'Beds are the most comforting place and space to be at after a tiring day or on a romantic eve. Designed with expertise using Hardwood MDF in mystic walnut and frosty white finish, Grey is remarkably the perfect solution to a tranquil and modern space customized bed designs. Wide headboard in white and walnut finish provides a feeling of comfort and luxury. This customizable bed is originally equipped with bottom storage and also features a vanity mirror and bedside tables on both the sides. Interior Solutions provides the facility of designing and making exquisite furniture for all the rooms anywhere in Bangalore, Kerala or Tamilnadu, within a specific time frame.', 105000.00, 1111, 983),
(74, 'Mocha', 'bedroom', 'bed', 'img/mocha.jpg', 'Bed designs that seamlessly blend in with any interiors are bliss. Mocha integrates a convenient and clean design that represents practicality and contemporary design aesthetics. Lustrous design and sophistication it carries creates a feeling of radiance with a touch of old world elegance. Crafted with high grade Hardwood MDF, this bed design with storage comes in classic grey wood and frosty white finish with bottom storage and an upholstered headboard. Additional furnishing includes bedside tables on both sides with dual drawers in dual tone finish. Visit Interior Solutions interior designers to get this elegant piece of décor for your contemporary space as part of interior works in Bengaluru, Kerala or Tamilnadu.', 85000.00, 816, 603),
(75, 'Legoland', 'bedroom', 'bed', 'img/legoland.jpg', 'Some prefer a decorative approach while designing the bedroom interior. When it comes to the usability and practicality, stylish ready-made, decorative beds often fail to satisfy the customers. However, customized bed designs like Legoland combine the stylish layouts with functionality as per client’s needs. This queen size bed has a contemporary layout with two side tables, headboard, and bottom storage.', 89000.00, 936, 846),
(76, 'Sintra', 'bedroom', 'bed', 'img/sintra.jpg', 'Contemporary interior design formulas give more eminence to beds than any other furniture item. Because, the flaws in this design might directly affect the occupant’s behavior and the rhythm of life. Sintra is such a design with an optimized structure combined with all the essential ingredients to ensure a smooth and healthy life-style. This premium bed follows the popular walnut bronze color theme for most of its parts, with an addition of a small layer of glossy white on the headboard. In addition to the aesthetic elegance, this beautiful queen size bed comes with a pair of bedside tables, table lamp, and a small overhead decorative unit for better convenience.', 130000.00, 2006, 1120),
(77, 'Scratch', 'bedroom', 'bed', 'img/scratch.jpg', 'Make the most of the bedroom space with this contemporary bed design. Designed to offer effortless space for the room without obstructions, Scratch has efficiently designed soft-close bedside tables with drawers on either side. Crafted with long-lasting Hardwood MDF in a blend of slate grey and irish cream colors, this bed is something that sets your bedroom apart. The modern hardboard with a clean-lined contemporary design matches every décor and can be paired easily in small spaces. This beautiful bed is customizable and can be made in queen or king-size beds. For enquiries, contact or Walk in to our nearest showrooms spread across Kerala, Tamilnadu or Bangalore.', 120000.00, 2113, 1509),
(78, 'Rafflesia', 'bedroom', 'bed', 'img/rafflesia.jpg', 'One should be more careful while selecting furniture or making interior choices for bedrooms. A suitable bed is the key element of bedroom interior; it dominates all the other furniture items and decorative items in this aspect. Beds should be functional, stylish, comfortable and appropriate for the occupants. Contemporary bed designs like Rafflesia are specifically designed to provide extreme comfort and distinctive style. It’s low height and excellent positioning makes it comfortable for both young and older individuals.', 95000.00, 926, 763);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `designs`
--
ALTER TABLE `designs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `designs`
--
ALTER TABLE `designs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
